-- PHARMACY SYSTEM DATA POPULATION SCRIPT

-- 1. POPULATE MEDICINES (20+ Records)
INSERT ALL
INTO Medicines (med_ID, med_category, name, description, price) VALUES (1, 'Analgesics', 'Paracetamol 500mg', 'Pain reliever and fever reducer.', 5.50)
INTO Medicines (med_ID, med_category, name, description, price) VALUES (2, 'Antibiotics', 'Amoxicillin 250mg', 'Used for bacterial infections.', 12.00)
INTO Medicines (med_ID, med_category, name, description, price) VALUES (3, 'Antihistamines', 'Cetirizine', 'Allergy relief.', 8.75)
INTO Medicines (med_ID, med_category, name, description, price) VALUES (4, 'Cardiovascular', 'Atorvastatin', 'Cholesterol management.', 22.30)
INTO Medicines (med_ID, med_category, name, description, price) VALUES (5, 'Antidiabetic', 'Metformin', 'Type 2 diabetes treatment.', 15.00)
INTO Medicines (med_ID, med_category, name, description, price) VALUES (6, 'Antiseptic', 'Povidone-Iodine', 'Wound disinfectant.', 6.25)
INTO Medicines (med_ID, med_category, name, description, price) VALUES (7, 'Vitamins', 'Vitamin C 1000mg', 'Immune system support.', 10.00)
INTO Medicines (med_ID, med_category, name, description, price) VALUES (8, 'Gastrointestinal', 'Omeprazole', 'Acid reflux relief.', 18.50)
INTO Medicines (med_ID, med_category, name, description, price) VALUES (9, 'Respiratory', 'Salbutamol Inhaler', 'Asthma symptom relief.', 25.00)
INTO Medicines (med_ID, med_category, name, description, price) VALUES (10, 'Analgesics', 'Ibuprofen 400mg', 'Anti-inflammatory and pain relief.', 7.20)
INTO Medicines (med_ID, med_category, name, description, price) VALUES (11, 'Antifungal', 'Clotrimazole Cream', 'Topical antifungal treatment.', 9.40)
INTO Medicines (med_ID, med_category, name, description, price) VALUES (12, 'Cardiovascular', 'Amlodipine', 'Blood pressure management.', 14.80)
INTO Medicines (med_ID, med_category, name, description, price) VALUES (13, 'Vitamins', 'Multivitamin Gold', 'Daily nutritional support.', 30.00)
INTO Medicines (med_ID, med_category, name, description, price) VALUES (14, 'Antibiotics', 'Azithromycin', 'Broad-spectrum antibiotic.', 20.00)
INTO Medicines (med_ID, med_category, name, description, price) VALUES (15, 'Analgesics', 'Aspirin 100mg', 'Blood thinner/pain relief.', 4.50)
INTO Medicines (med_ID, med_category, name, description, price) VALUES (16, 'Antidiabetic', 'Insulin Glargine', 'Long-acting insulin.', 55.00)
INTO Medicines (med_ID, med_category, name, description, price) VALUES (17, 'Dermatology', 'Hydrocortisone', 'Steroid cream for skin irritation.', 11.15)
INTO Medicines (med_ID, med_category, name, description, price) VALUES (18, 'Gastrointestinal', 'Loperamide', 'Anti-diarrheal medication.', 5.90)
INTO Medicines (med_ID, med_category, name, description, price) VALUES (19, 'Ophthalmology', 'Hypromellose Drops', 'Artificial tears for dry eyes.', 13.25)
INTO Medicines (med_ID, med_category, name, description, price) VALUES (20, 'Nervous System', 'Diazepam', 'Anxiety and seizure control.', 19.00)
SELECT * FROM dual;

-- 2. POPULATE CUSTOMERS (20+ Records)
INSERT ALL
INTO Customer VALUES (101, 'James', 'Smith', 'Male', 34, '123 Maple St, NY', 'james.s@email.com', 'pass123')
INTO Customer VALUES (102, 'Maria', 'Garcia', 'Female', 28, '456 Oak Ave, CA', 'm.garcia@email.com', 'secure789')
INTO Customer VALUES (103, 'Robert', 'Johnson', 'Male', 52, '789 Pine Rd, TX', 'rob.j@email.com', 'robpass')
INTO Customer VALUES (104, 'Linda', 'Williams', 'Female', 41, '321 Elm St, FL', 'linda.w@email.com', 'linda123')
INTO Customer VALUES (105, 'Michael', 'Brown', 'Male', 65, '654 Cedar Ln, IL', 'm.brown@email.com', 'brownie65')
INTO Customer VALUES (106, 'Sarah', 'Davis', 'Female', 19, '987 Birch Way, WA', 'sarah.d@email.com', 'sarah99')
INTO Customer VALUES (107, 'David', 'Miller', 'Male', 44, '159 Willow Dr, GA', 'dave.m@email.com', 'dave44')
INTO Customer VALUES (108, 'Susan', 'Wilson', 'Female', 31, '753 Aspen Ct, CO', 'susan.w@email.com', 'sue_wil')
INTO Customer VALUES (109, 'Chris', 'Moore', 'Male', 25, '852 Spruce Pt, MI', 'chris.m@email.com', 'moore_c')
INTO Customer VALUES (110, 'Karen', 'Taylor', 'Female', 58, '951 Hemlock St, OH', 'karen.t@email.com', 'ktaylor')
INTO Customer VALUES (111, 'John', 'Anderson', 'Male', 37, '147 Larch Ave, PA', 'john.a@email.com', 'johnny1')
INTO Customer VALUES (112, 'Nancy', 'Thomas', 'Female', 62, '258 Fir Blvd, OR', 'nancy.t@email.com', 'nancy62')
INTO Customer VALUES (113, 'Paul', 'Jackson', 'Male', 22, '369 Poplar Pl, AZ', 'paul.j@email.com', 'paul_az')
INTO Customer VALUES (114, 'Lisa', 'White', 'Female', 47, '741 Alder Rd, NV', 'lisa.w@email.com', 'lisawhite')
INTO Customer VALUES (115, 'Kevin', 'Harris', 'Male', 29, '852 Beech St, TN', 'kevin.h@email.com', 'kev_h')
INTO Customer VALUES (116, 'Anna', 'Martin', 'Female', 33, '963 Cherry Ln, KY', 'anna.m@email.com', 'anna33')
INTO Customer VALUES (117, 'Gary', 'Thompson', 'Male', 55, '159 Walnut Dr, NC', 'gary.t@email.com', 'gary_t')
INTO Customer VALUES (118, 'Ruth', 'Garcia', 'Female', 70, '357 Chestnut St, VA', 'ruth.g@email.com', 'ruth70')
INTO Customer VALUES (119, 'Eric', 'Young', 'Male', 26, '456 Sycamore Ave, UT', 'eric.y@email.com', 'eric_y')
INTO Customer VALUES (120, 'Amy', 'King', 'Female', 39, '789 Magnolia Dr, SC', 'amy.k@email.com', 'amy_king')
SELECT * FROM dual;

-- 3. POPULATE PHARMACISTS (20+ Records)
INSERT ALL
INTO Pharmacist VALUES (201, 'Sarah', 'Miller', 'Female', 29, '101 Med Blvd, NY', 'sarah.m@pharmacy.com', 'admin1')
INTO Pharmacist VALUES (202, 'David', 'Wilson', 'Male', 35, '202 Health Way, NY', 'david.w@pharmacy.com', 'admin2')
INTO Pharmacist VALUES (203, 'Elena', 'Rodriguez', 'Female', 42, '303 Care St, NY', 'elena.r@pharmacy.com', 'admin3')
INTO Pharmacist VALUES (204, 'Kevin', 'Lee', 'Male', 31, '404 Pharma Ave, NY', 'kevin.l@pharmacy.com', 'admin4')
INTO Pharmacist VALUES (205, 'Chloe', 'Smith', 'Female', 27, '505 Wellness Dr, NY', 'chloe.s@pharmacy.com', 'admin5')
INTO Pharmacist VALUES (206, 'Mark', 'Boucher', 'Male', 38, '606 Cure Rd, NY', 'mark.b@pharmacy.com', 'admin6')
INTO Pharmacist VALUES (207, 'Julia', 'Taft', 'Female', 45, '707 Pill Ln, NY', 'julia.t@pharmacy.com', 'admin7')
INTO Pharmacist VALUES (208, 'Brian', 'May', 'Male', 33, '808 Dose Blvd, NY', 'brian.m@pharmacy.com', 'admin8')
INTO Pharmacist VALUES (209, 'Sophie', 'Turner', 'Female', 26, '909 Aid St, NY', 'sophie.t@pharmacy.com', 'admin9')
INTO Pharmacist VALUES (210, 'Adam', 'Scott', 'Male', 50, '111 Script Rd, NY', 'adam.s@pharmacy.com', 'admin10')
INTO Pharmacist VALUES (211, 'Lily', 'Evans', 'Female', 30, '222 Drug St, NY', 'lily.e@pharmacy.com', 'admin11')
INTO Pharmacist VALUES (212, 'Ryan', 'Gosling', 'Male', 41, '333 Med Way, NY', 'ryan.g@pharmacy.com', 'admin12')
INTO Pharmacist VALUES (213, 'Emma', 'Stone', 'Female', 28, '444 Health Ct, NY', 'emma.s@pharmacy.com', 'admin13')
INTO Pharmacist VALUES (214, 'Tom', 'Hardy', 'Male', 44, '555 Care Blvd, NY', 'tom.h@pharmacy.com', 'admin14')
INTO Pharmacist VALUES (215, 'Claire', 'Danes', 'Female', 37, '666 Wellness St, NY', 'claire.d@pharmacy.com', 'admin15')
INTO Pharmacist VALUES (216, 'Jason', 'Momoa', 'Male', 39, '777 Pharma Ln, NY', 'jason.m@pharmacy.com', 'admin16')
INTO Pharmacist VALUES (217, 'Adele', 'Adkins', 'Female', 32, '888 Cure Way, NY', 'adele.a@pharmacy.com', 'admin17')
INTO Pharmacist VALUES (218, 'Chris', 'Pratt', 'Male', 40, '999 Pill Rd, NY', 'chris.p@pharmacy.com', 'admin18')
INTO Pharmacist VALUES (219, 'Gal', 'Gadot', 'Female', 35, '121 Aid Ave, NY', 'gal.g@pharmacy.com', 'admin19')
INTO Pharmacist VALUES (220, 'Henry', 'Cavill', 'Male', 38, '232 Script St, NY', 'henry.c@pharmacy.com', 'admin20')
SELECT * FROM dual;

-- 4. POPULATE PURCHASING (Linking Customers and Medicines)
INSERT ALL
INTO Purchasing (purchase_ID, cust_ID, med_ID, amount) VALUES (301, 101, 1, 11.00)
INTO Purchasing (purchase_ID, cust_ID, med_ID, amount) VALUES (302, 102, 3, 8.75)
INTO Purchasing (purchase_ID, cust_ID, med_ID, amount) VALUES (303, 103, 4, 44.60)
INTO Purchasing (purchase_ID, cust_ID, med_ID, amount) VALUES (304, 104, 2, 12.00)
INTO Purchasing (purchase_ID, cust_ID, med_ID, amount) VALUES (305, 105, 5, 15.00)
INTO Purchasing (purchase_ID, cust_ID, med_ID, amount) VALUES (306, 106, 7, 10.00)
INTO Purchasing (purchase_ID, cust_ID, med_ID, amount) VALUES (307, 107, 9, 50.00)
INTO Purchasing (purchase_ID, cust_ID, med_ID, amount) VALUES (308, 108, 10, 7.20)
INTO Purchasing (purchase_ID, cust_ID, med_ID, amount) VALUES (309, 109, 12, 14.80)
INTO Purchasing (purchase_ID, cust_ID, med_ID, amount) VALUES (310, 110, 15, 4.50)
INTO Purchasing (purchase_ID, cust_ID, med_ID, amount) VALUES (311, 111, 1, 5.50)
INTO Purchasing (purchase_ID, cust_ID, med_ID, amount) VALUES (312, 112, 13, 60.00)
INTO Purchasing (purchase_ID, cust_ID, med_ID, amount) VALUES (313, 113, 2, 24.00)
INTO Purchasing (purchase_ID, cust_ID, med_ID, amount) VALUES (314, 114, 17, 11.15)
INTO Purchasing (purchase_ID, cust_ID, med_ID, amount) VALUES (315, 115, 8, 18.50)
INTO Purchasing (purchase_ID, cust_ID, med_ID, amount) VALUES (316, 116, 20, 19.00)
INTO Purchasing (purchase_ID, cust_ID, med_ID, amount) VALUES (317, 117, 4, 22.30)
INTO Purchasing (purchase_ID, cust_ID, med_ID, amount) VALUES (318, 118, 16, 110.00)
INTO Purchasing (purchase_ID, cust_ID, med_ID, amount) VALUES (319, 119, 6, 6.25)
INTO Purchasing (purchase_ID, cust_ID, med_ID, amount) VALUES (320, 120, 11, 9.40)
SELECT * FROM dual;

-- 5. POPULATE SALES (Linking Pharmacists to Purchases)
INSERT ALL
INTO Sales (sales_ID, phar_ID, cust_ID, med_ID, count, purchase_ID, total_amount) VALUES (401, 201, 101, 1, 2, 301, 11.00)
INTO Sales (sales_ID, phar_ID, cust_ID, med_ID, count, purchase_ID, total_amount) VALUES (402, 202, 102, 3, 1, 302, 8.75)
INTO Sales (sales_ID, phar_ID, cust_ID, med_ID, count, purchase_ID, total_amount) VALUES (403, 203, 103, 4, 2, 303, 44.60)
INTO Sales (sales_ID, phar_ID, cust_ID, med_ID, count, purchase_ID, total_amount) VALUES (404, 204, 104, 2, 1, 304, 12.00)
INTO Sales (sales_ID, phar_ID, cust_ID, med_ID, count, purchase_ID, total_amount) VALUES (405, 205, 105, 5, 1, 305, 15.00)
INTO Sales (sales_ID, phar_ID, cust_ID, med_ID, count, purchase_ID, total_amount) VALUES (406, 201, 106, 7, 1, 306, 10.00)
INTO Sales (sales_ID, phar_ID, cust_ID, med_ID, count, purchase_ID, total_amount) VALUES (407, 202, 107, 9, 2, 307, 50.00)
INTO Sales (sales_ID, phar_ID, cust_ID, med_ID, count, purchase_ID, total_amount) VALUES (408, 203, 108, 10, 1, 308, 7.20)
INTO Sales (sales_ID, phar_ID, cust_ID, med_ID, count, purchase_ID, total_amount) VALUES (409, 204, 109, 12, 1, 309, 14.80)
INTO Sales (sales_ID, phar_ID, cust_ID, med_ID, count, purchase_ID, total_amount) VALUES (410, 205, 110, 15, 1, 310, 4.50)
INTO Sales (sales_ID, phar_ID, cust_ID, med_ID, count, purchase_ID, total_amount) VALUES (411, 206, 111, 1, 1, 311, 5.50)
INTO Sales (sales_ID, phar_ID, cust_ID, med_ID, count, purchase_ID, total_amount) VALUES (412, 207, 112, 13, 2, 312, 60.00)
INTO Sales (sales_ID, phar_ID, cust_ID, med_ID, count, purchase_ID, total_amount) VALUES (413, 208, 113, 2, 2, 313, 24.00)
INTO Sales (sales_ID, phar_ID, cust_ID, med_ID, count, purchase_ID, total_amount) VALUES (414, 209, 114, 17, 1, 314, 11.15)
INTO Sales (sales_ID, phar_ID, cust_ID, med_ID, count, purchase_ID, total_amount) VALUES (415, 210, 115, 8, 1, 315, 18.50)
INTO Sales (sales_ID, phar_ID, cust_ID, med_ID, count, purchase_ID, total_amount) VALUES (416, 211, 116, 20, 1, 316, 19.00)
INTO Sales (sales_ID, phar_ID, cust_ID, med_ID, count, purchase_ID, total_amount) VALUES (417, 212, 117, 4, 1, 317, 22.30)
INTO Sales (sales_ID, phar_ID, cust_ID, med_ID, count, purchase_ID, total_amount) VALUES (418, 213, 118, 16, 2, 318, 110.00)
INTO Sales (sales_ID, phar_ID, cust_ID, med_ID, count, purchase_ID, total_amount) VALUES (419, 214, 119, 6, 1, 319, 6.25)
INTO Sales (sales_ID, phar_ID, cust_ID, med_ID, count, purchase_ID, total_amount) VALUES (420, 215, 120, 11, 1, 320, 9.40)
SELECT * FROM dual;

-- 6. POPULATE REPORTS
INSERT ALL
INTO Reports (report_ID, purchase_ID, sales_ID, cust_ID) VALUES (601, 301, 401, 101)
INTO Reports (report_ID, purchase_ID, sales_ID, cust_ID) VALUES (602, 302, 402, 102)
INTO Reports (report_ID, purchase_ID, sales_ID, cust_ID) VALUES (603, 303, 403, 103)
INTO Reports (report_ID, purchase_ID, sales_ID, cust_ID) VALUES (604, 304, 404, 104)
INTO Reports (report_ID, purchase_ID, sales_ID, cust_ID) VALUES (605, 305, 405, 105)
INTO Reports (report_ID, purchase_ID, sales_ID, cust_ID) VALUES (606, 306, 406, 106)
INTO Reports (report_ID, purchase_ID, sales_ID, cust_ID) VALUES (607, 307, 407, 107)
INTO Reports (report_ID, purchase_ID, sales_ID, cust_ID) VALUES (608, 308, 408, 108)
INTO Reports (report_ID, purchase_ID, sales_ID, cust_ID) VALUES (609, 309, 409, 109)
INTO Reports (report_ID, purchase_ID, sales_ID, cust_ID) VALUES (610, 310, 410, 110)
INTO Reports (report_ID, purchase_ID, sales_ID, cust_ID) VALUES (611, 311, 411, 111)
INTO Reports (report_ID, purchase_ID, sales_ID, cust_ID) VALUES (612, 312, 412, 112)
INTO Reports (report_ID, purchase_ID, sales_ID, cust_ID) VALUES (613, 313, 413, 113)
INTO Reports (report_ID, purchase_ID, sales_ID, cust_ID) VALUES (614, 314, 414, 114)
INTO Reports (report_ID, purchase_ID, sales_ID, cust_ID) VALUES (615, 315, 415, 115)
INTO Reports (report_ID, purchase_ID, sales_ID, cust_ID) VALUES (616, 316, 416, 116)
INTO Reports (report_ID, purchase_ID, sales_ID, cust_ID) VALUES (617, 317, 417, 117)
INTO Reports (report_ID, purchase_ID, sales_ID, cust_ID) VALUES (618, 318, 418, 118)
INTO Reports (report_ID, purchase_ID, sales_ID, cust_ID) VALUES (619, 319, 419, 119)
INTO Reports (report_ID, purchase_ID, sales_ID, cust_ID) VALUES (620, 320, 420, 120)
SELECT * FROM dual;

COMMIT;