-- =============================================
-- REFINED PHARMACY MANAGEMENT SYSTEM (CASCADE DELETE)
-- =============================================

-- 1. Medicines Table (Parent)
CREATE TABLE Medicines (
    med_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    med_category VARCHAR2(100),
    name VARCHAR2(200) NOT NULL,
    description CLOB,
    price NUMBER(10, 2) NOT NULL,
    photo BLOB,
    stock NUMBER(10) DEFAULT 0,
    min_stock_level NUMBER(10) DEFAULT 5
);

-- 2. Customer Table (Parent)
CREATE TABLE Customer (
    cust_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fname VARCHAR2(50),
    lname VARCHAR2(50),
    gender VARCHAR2(10),
    age NUMBER(3),
    contact_add VARCHAR2(255),
    cust_email VARCHAR2(100) UNIQUE NOT NULL,
    cust_pass VARCHAR2(100) NOT NULL,
    photo BLOB
);

-- 3. Pharmacist Table (Parent)
CREATE TABLE Pharmacist (
    phar_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fname VARCHAR2(50) NOT NULL,
    lname VARCHAR2(50) NOT NULL,
    gender VARCHAR2(10),
    age NUMBER(3),
    contact_add VARCHAR2(255),
    admin_email VARCHAR2(100) UNIQUE NOT NULL,
    admin_pass VARCHAR2(100) NOT NULL,
    photo BLOB
);

-- 4. Purchasing Table
-- If a Customer or Medicine is deleted, the purchase record is removed.
CREATE TABLE Purchasing (
    purchase_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cust_ID NUMBER NOT NULL,
    med_ID NUMBER NOT NULL,
    quantity NUMBER(10) NOT NULL, 
    purchase_date DATE DEFAULT SYSDATE,
    CONSTRAINT fk_pur_cust FOREIGN KEY (cust_ID) 
        REFERENCES Customer(cust_ID) ON DELETE CASCADE,
    CONSTRAINT fk_pur_med FOREIGN KEY (med_ID) 
        REFERENCES Medicines(med_ID) ON DELETE CASCADE
);

-- 5. Sales Table
-- If a Pharmacist or the original Purchase record is deleted, the sale record is removed.
CREATE TABLE Sales (
    sales_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phar_ID NUMBER NOT NULL,
    purchase_ID NUMBER NOT NULL, 
    unit_price_at_sale NUMBER(10, 2),
    total_amount NUMBER(10, 2), 
    sale_date DATE DEFAULT SYSDATE,
    CONSTRAINT fk_sales_phar FOREIGN KEY (phar_ID) 
        REFERENCES Pharmacist(phar_ID) ON DELETE CASCADE,
    CONSTRAINT fk_sales_pur FOREIGN KEY (purchase_ID) 
        REFERENCES Purchasing(purchase_ID) ON DELETE CASCADE
);
-- =============================================
-- ALL-IN-ONE AUTOMATION TRIGGER
-- =============================================

CREATE OR REPLACE TRIGGER trg_process_complete_sale
BEFORE INSERT ON Sales
FOR EACH ROW
DECLARE
    v_unit_price NUMBER(10, 2);
    v_qty NUMBER;
    v_med_id NUMBER;
    v_current_stock NUMBER;
BEGIN
    -- 1. Fetch details from the linked Purchase record
    SELECT med_ID, quantity INTO v_med_id, v_qty 
    FROM Purchasing 
    WHERE purchase_ID = :NEW.purchase_ID;

    -- 2. Fetch price and stock from Medicines
    SELECT price, stock INTO v_unit_price, v_current_stock 
    FROM Medicines 
    WHERE med_ID = v_med_id;

    -- 3. Validation: Check if there is enough stock
    IF v_current_stock < v_qty THEN
        RAISE_APPLICATION_ERROR(-20001, 'Transaction Failed: Insufficient stock for this medicine.');
    END IF;

    -- 4. Data Integrity: Set the prices in the Sales record
    :NEW.unit_price_at_sale := v_unit_price;
    :NEW.total_amount := v_unit_price * v_qty;

    -- 5. Inventory Update: Automatically reduce the stock
    UPDATE Medicines 
    SET stock = stock - v_qty 
    WHERE med_ID = v_med_id;
END;
/