-- =============================================
-- PHARMACY MANAGEMENT SYSTEM SCRIPT
-- =============================================

-- 1. Medicines Table (Updated with min_stock_level)
CREATE TABLE Medicines (
    med_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    med_category VARCHAR2(100),
    name VARCHAR2(200) NOT NULL,
    description CLOB,
    price NUMBER(10, 2) NOT NULL,
    photo BLOB,
    stock NUMBER(10) DEFAULT 0,
    min_stock_level NUMBER(10) DEFAULT 5 -- Part D: Inventory Management
);

-- 2. Customer Table
CREATE TABLE Customer (
    cust_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fname VARCHAR2(50) NOT NULL,
    lname VARCHAR2(50) NOT NULL,
    gender VARCHAR2(10),
    age NUMBER(3),
    contact_add VARCHAR2(255),
    cust_email VARCHAR2(100) UNIQUE NOT NULL,
    cust_pass VARCHAR2(100) NOT NULL,
    photo BLOB
);

-- 3. Pharmacist Table
CREATE TABLE Pharmacist (
    phar_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fname VARCHAR2(50) NOT NULL,
    lname VARCHAR2(50) NOT NULL,
    gender VARCHAR2(10),
    age NUMBER(3),
    contact_add VARCHAR2(255),
    admin_email VARCHAR2(100) UNIQUE NOT NULL,
    admin_pass VARCHAR2(100) NOT NULL,
    photo BLOB
);

-- 4. Purchasing Table
CREATE TABLE Purchasing (
    purchase_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cust_ID NUMBER NOT NULL,
    med_ID NUMBER NOT NULL,
    amount NUMBER(10, 2) NOT NULL,
    purchase_date DATE DEFAULT SYSDATE,
    CONSTRAINT fk_pur_cust FOREIGN KEY (cust_ID) REFERENCES Customer(cust_ID),
    CONSTRAINT fk_pur_med FOREIGN KEY (med_ID) REFERENCES Medicines(med_ID)
);

-- 5. Sales Table
CREATE TABLE Sales (
    sales_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phar_ID NUMBER NOT NULL,
    cust_ID NUMBER NOT NULL,
    med_ID NUMBER NOT NULL,
    count NUMBER NOT NULL,
    purchase_ID NUMBER,
    sale_date DATE DEFAULT SYSDATE,
    total_amount NUMBER(10, 2), -- Now automated via trigger
    CONSTRAINT fk_sales_phar FOREIGN KEY (phar_ID) REFERENCES Pharmacist(phar_ID),
    CONSTRAINT fk_sales_cust FOREIGN KEY (cust_ID) REFERENCES Customer(cust_ID),
    CONSTRAINT fk_sales_med FOREIGN KEY (med_ID) REFERENCES Medicines(med_ID),
    CONSTRAINT fk_sales_pur FOREIGN KEY (purchase_ID) REFERENCES Purchasing(purchase_ID)
);

-- =============================================
-- TRIGGERS FOR AUTOMATION
-- =============================================

-- NEW TRIGGER: Part A - Automatically calculate total price
CREATE OR REPLACE TRIGGER trg_calculate_sale_total
BEFORE INSERT ON Sales
FOR EACH ROW
DECLARE
    v_unit_price NUMBER(10, 2);
BEGIN
    SELECT price INTO v_unit_price 
    FROM Medicines 
    WHERE med_ID = :NEW.med_ID;

    :NEW.total_amount := v_unit_price * :NEW.count;
END;
/

-- TRIGGER: Prevent a sale if stock is insufficient
CREATE OR REPLACE TRIGGER trg_check_stock_before_sale
BEFORE INSERT ON Sales
FOR EACH ROW
DECLARE
    v_current_stock NUMBER;
BEGIN
    SELECT stock INTO v_current_stock 
    FROM Medicines 
    WHERE med_ID = :NEW.med_ID;

    IF v_current_stock < :NEW.count THEN
        RAISE_APPLICATION_ERROR(-20001, 'Insufficient stock for this medicine!');
    END IF;
END;
/

-- TRIGGER: Automatically reduce stock when a sale is made
CREATE OR REPLACE TRIGGER trg_update_stock
AFTER INSERT ON Sales
FOR EACH ROW
BEGIN
    UPDATE Medicines
    SET stock = stock - :NEW.count
    WHERE med_ID = :NEW.med_ID;
END;
/